external_data_config:
  external_data_csv: data/external/boston.csv


raw_data_config:
  raw_data_csv: data/raw/boston.csv
  model_var: ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']

  train_test_split_ratio: 0.2
  target: MEDV
  random_state: 111
  new_train_data_csv: data/raw/train_new.csv

processed_data_config:
  train_data_csv: data/processed/boston_train.csv
  test_data_csv:  data/processed/boston_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: linear_regression
  registered_model_name: linear_regression_model
  remote_server_uri: http://localhost:1234

linear_regression:
  fit_intercept: True

model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html